//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilize.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilize.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 332 326 1 1 180 213 Kerman;
        ///483 341 181 1 155 243 Sistan_va_Balochestan;
        ///279 448 336 1 220 129 Hormozgan;
        ///210 338 556 1 169 178 Fars;
        ///189 391 725 1 79 104 Boshehr;
        ///436 240 804 1 108 139 Khorasan_Gonobi;
        ///382 107 912 1 166 160 Khorasan_Razavi;
        ///193 205 1078 1 62 39 Ghom;
        ///200 163 1140 1 92 55 Tehran;
        ///281 207 1232 1 176 213 Yazd;
        ///178 231 1408 1 184 141 Isfahan;
        ///252 132 1592 1 160 111 Semnan;
        ///372 86 1752 1 84 68 Khorasan_Shomaly;
        ///315 93 1836 1 77 65 Golestan;
        ///207 137 1913 1 120 47 Mazendran;
        ///185 34 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strMapInf {
            get {
                return ResourceManager.GetString("strMapInf", resourceCulture);
            }
        }
    }
}
