//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResLabel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResLabel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Properties.ResLabel", typeof(ResLabel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Branch.
        /// </summary>
        internal static string AccBranch {
            get {
                return ResourceManager.GetString("AccBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acc Lvl.
        /// </summary>
        internal static string AccLvl {
            get {
                return ResourceManager.GetString("AccLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Group Model.
        /// </summary>
        internal static string AccountGroupModel {
            get {
                return ResourceManager.GetString("AccountGroupModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountsGL.
        /// </summary>
        internal static string AccountsGL {
            get {
                return ResourceManager.GetString("AccountsGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collateral Loan Report.
        /// </summary>
        internal static string CollateralOfLoanReport {
            get {
                return ResourceManager.GetString("CollateralOfLoanReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collateral Tarhini And Total Overdue.
        /// </summary>
        internal static string CollateralTarhiniAndTotalOverdue {
            get {
                return ResourceManager.GetString("CollateralTarhiniAndTotalOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContractType.
        /// </summary>
        internal static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterparty.
        /// </summary>
        internal static string Counterparty {
            get {
                return ResourceManager.GetString("Counterparty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Report Historic.
        /// </summary>
        internal static string CreditReportHistoric {
            get {
                return ResourceManager.GetString("CreditReportHistoric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency All.
        /// </summary>
        internal static string CurrencyAll {
            get {
                return ResourceManager.GetString("CurrencyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Chart.
        /// </summary>
        internal static string DepositChart {
            get {
                return ResourceManager.GetString("DepositChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Modeling.
        /// </summary>
        internal static string DepositModeling {
            get {
                return ResourceManager.GetString("DepositModeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Range Report.
        /// </summary>
        internal static string DepositRangeReport {
            get {
                return ResourceManager.GetString("DepositRangeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Report.
        /// </summary>
        internal static string DepositReport {
            get {
                return ResourceManager.GetString("DepositReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economic Capital.
        /// </summary>
        internal static string EconomicCapital {
            get {
                return ResourceManager.GetString("EconomicCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficient Stock.
        /// </summary>
        internal static string EfficientStock {
            get {
                return ResourceManager.GetString("EfficientStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Logs.
        /// </summary>
        internal static string EventLogs {
            get {
                return ResourceManager.GetString("EventLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Ratio Define.
        /// </summary>
        internal static string FinancialRatioDefine {
            get {
                return ResourceManager.GetString("FinancialRatioDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Ratio Model.
        /// </summary>
        internal static string FinancialRatioModel {
            get {
                return ResourceManager.GetString("FinancialRatioModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Statement.
        /// </summary>
        internal static string FinancialStatement {
            get {
                return ResourceManager.GetString("FinancialStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap Analysis.
        /// </summary>
        internal static string GapAnalysis {
            get {
                return ResourceManager.GetString("GapAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap Report.
        /// </summary>
        internal static string GapReport {
            get {
                return ResourceManager.GetString("GapReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap Trending Report.
        /// </summary>
        internal static string GapTrendingReport {
            get {
                return ResourceManager.GetString("GapTrendingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Deposit Report.
        /// </summary>
        internal static string HistoricalDepositReport {
            get {
                return ResourceManager.GetString("HistoricalDepositReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Rate Curves.
        /// </summary>
        internal static string InterestRateCurves {
            get {
                return ResourceManager.GetString("InterestRateCurves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items with no maturity Model.
        /// </summary>
        internal static string ItemsWithNoMaturityModel {
            get {
                return ResourceManager.GetString("ItemsWithNoMaturityModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Management.
        /// </summary>
        internal static string LimitManagement {
            get {
                return ResourceManager.GetString("LimitManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Report.
        /// </summary>
        internal static string LimitReport {
            get {
                return ResourceManager.GetString("LimitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoanCalc.
        /// </summary>
        internal static string LoanCalc {
            get {
                return ResourceManager.GetString("LoanCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Repor.
        /// </summary>
        internal static string LoanRepor {
            get {
                return ResourceManager.GetString("LoanRepor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Report Historic.
        /// </summary>
        internal static string LoanReportHistor {
            get {
                return ResourceManager.GetString("LoanReportHistor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Total Report.
        /// </summary>
        internal static string LoanTotalReport {
            get {
                return ResourceManager.GetString("LoanTotalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Logs.
        /// </summary>
        internal static string ManagementLogs {
            get {
                return ResourceManager.GetString("ManagementLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Management.
        /// </summary>
        internal static string ModelManagement {
            get {
                return ResourceManager.GetString("ModelManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR1.
        /// </summary>
        internal static string MR1 {
            get {
                return ResourceManager.GetString("MR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR2.
        /// </summary>
        internal static string MR2 {
            get {
                return ResourceManager.GetString("MR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR3.
        /// </summary>
        internal static string MR3 {
            get {
                return ResourceManager.GetString("MR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR4.
        /// </summary>
        internal static string MR4 {
            get {
                return ResourceManager.GetString("MR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Interest Income.
        /// </summary>
        internal static string NetInterestIncome {
            get {
                return ResourceManager.GetString("NetInterestIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Loan Report.
        /// </summary>
        internal static string RangeLoanReport {
            get {
                return ResourceManager.GetString("RangeLoanReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation.
        /// </summary>
        internal static string Reconciliation {
            get {
                return ResourceManager.GetString("Reconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Column.
        /// </summary>
        internal static string SettingShowTitleOfColumn {
            get {
                return ResourceManager.GetString("SettingShowTitleOfColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Report Loan.
        /// </summary>
        internal static string SpecialReportLoan {
            get {
                return ResourceManager.GetString("SpecialReportLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Bucket.
        /// </summary>
        internal static string TimeBucket {
            get {
                return ResourceManager.GetString("TimeBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
    }
}
