//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResLabel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResLabel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Properties.ResLabel", typeof(ResLabel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفتر کل شعب.
        /// </summary>
        internal static string AccBranch {
            get {
                return ResourceManager.GetString("AccBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی.
        /// </summary>
        internal static string AccLvl {
            get {
                return ResourceManager.GetString("AccLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه های حسابداری.
        /// </summary>
        internal static string AccountGroupModel {
            get {
                return ResourceManager.GetString("AccountGroupModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش حسابداری.
        /// </summary>
        internal static string AccountReport {
            get {
                return ResourceManager.GetString("AccountReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفتر کل.
        /// </summary>
        internal static string AccountsGL {
            get {
                return ResourceManager.GetString("AccountsGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل فعال : {0}.
        /// </summary>
        internal static string Act_Profile {
            get {
                return ResourceManager.GetString("Act_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعبه.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش وثایق.
        /// </summary>
        internal static string CollateralOfLoanReport {
            get {
                return ResourceManager.GetString("CollateralOfLoanReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت وثیقه.
        /// </summary>
        internal static string CollateralStatus {
            get {
                return ResourceManager.GetString("CollateralStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزش معوقات به وثایق.
        /// </summary>
        internal static string CollateralTarhiniAndTotalOverdue {
            get {
                return ResourceManager.GetString("CollateralTarhiniAndTotalOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع وثیقه.
        /// </summary>
        internal static string CollateralType {
            get {
                return ResourceManager.GetString("CollateralType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع اصلی وثیقه.
        /// </summary>
        internal static string CollatMajorType {
            get {
                return ResourceManager.GetString("CollatMajorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کلی قرارداد.
        /// </summary>
        internal static string ContractMajorType {
            get {
                return ResourceManager.GetString("ContractMajorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت قرارداد.
        /// </summary>
        internal static string ContractStatus {
            get {
                return ResourceManager.GetString("ContractStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع قرارداد.
        /// </summary>
        internal static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع اصلی قرارداد.
        /// </summary>
        internal static string ContractTypeGroups {
            get {
                return ResourceManager.GetString("ContractTypeGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه مشتریان.
        /// </summary>
        internal static string CostumerGroup {
            get {
                return ResourceManager.GetString("CostumerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری.
        /// </summary>
        internal static string Counterparty {
            get {
                return ResourceManager.GetString("Counterparty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مشتریان.
        /// </summary>
        internal static string CounterPartyType {
            get {
                return ResourceManager.GetString("CounterPartyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش ریسک تمرکز.
        /// </summary>
        internal static string CreditReportHistoric {
            get {
                return ResourceManager.GetString("CreditReportHistoric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزش در خطر ارز.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزش در خطر کل ارز.
        /// </summary>
        internal static string CurrencyAll {
            get {
                return ResourceManager.GetString("CurrencyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدل رفتاری مشتری.
        /// </summary>
        internal static string DepositBehaviourModeling {
            get {
                return ResourceManager.GetString("DepositBehaviourModeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمودار سپرده ها.
        /// </summary>
        internal static string DepositChart {
            get {
                return ResourceManager.GetString("DepositChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدل سازی سپرده ها.
        /// </summary>
        internal static string DepositModeling {
            get {
                return ResourceManager.GetString("DepositModeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش بازه سازی سپرده ها.
        /// </summary>
        internal static string DepositRangeReport {
            get {
                return ResourceManager.GetString("DepositRangeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش سپرده ها.
        /// </summary>
        internal static string DepositReport {
            get {
                return ResourceManager.GetString("DepositReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرمایه اقتصادی.
        /// </summary>
        internal static string EconomicCapital {
            get {
                return ResourceManager.GetString("EconomicCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کفایت سرمایه.
        /// </summary>
        internal static string EfficientStock {
            get {
                return ResourceManager.GetString("EfficientStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقایع نگاشت.
        /// </summary>
        internal static string EventLogs {
            get {
                return ResourceManager.GetString("EventLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف فرمول نسبت های مالی.
        /// </summary>
        internal static string FinancialRatioDefine {
            get {
                return ResourceManager.GetString("FinancialRatioDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدل سازی نسبت های مالی.
        /// </summary>
        internal static string FinancialRatioModel {
            get {
                return ResourceManager.GetString("FinancialRatioModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدل ترازنامه.
        /// </summary>
        internal static string FinancialStatement {
            get {
                return ResourceManager.GetString("FinancialStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحلیل شکاف.
        /// </summary>
        internal static string GapAnalysis {
            get {
                return ResourceManager.GetString("GapAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدل رفتاری تحلیل شکاف.
        /// </summary>
        internal static string GapAnalysisBehaviorModeling {
            get {
                return ResourceManager.GetString("GapAnalysisBehaviorModeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش تاریخی تحلیل شکاف.
        /// </summary>
        internal static string GapReport {
            get {
                return ResourceManager.GetString("GapReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش روندگیری تحلیل شکاف.
        /// </summary>
        internal static string GapTrendingReport {
            get {
                return ResourceManager.GetString("GapTrendingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش تاریخی سپرده ها.
        /// </summary>
        internal static string HistoricalDepositReport {
            get {
                return ResourceManager.GetString("HistoricalDepositReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدل منحنی سود.
        /// </summary>
        internal static string InterestRateCurves {
            get {
                return ResourceManager.GetString("InterestRateCurves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدل اقلام بدون سررسید.
        /// </summary>
        internal static string ItemsWithNoMaturityModel {
            get {
                return ResourceManager.GetString("ItemsWithNoMaturityModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین به روزرسانی داده : {0}.
        /// </summary>
        internal static string LastUpdateDate {
            get {
                return ResourceManager.GetString("LastUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت حدود.
        /// </summary>
        internal static string LimitManagement {
            get {
                return ResourceManager.GetString("LimitManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش های مدیریت حدود.
        /// </summary>
        internal static string LimitReport {
            get {
                return ResourceManager.GetString("LimitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محاسبه تسهیلات.
        /// </summary>
        internal static string LoanCalc {
            get {
                return ResourceManager.GetString("LoanCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش سپرده ها.
        /// </summary>
        internal static string LoanRepor {
            get {
                return ResourceManager.GetString("LoanRepor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش تسهیلات.
        /// </summary>
        internal static string LoanReportCs {
            get {
                return ResourceManager.GetString("LoanReportCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش تاریخی تسهیلات.
        /// </summary>
        internal static string LoanReportHistor {
            get {
                return ResourceManager.GetString("LoanReportHistor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش جامع.
        /// </summary>
        internal static string LoanTotalReport {
            get {
                return ResourceManager.GetString("LoanTotalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ولقع نگاشت های مدیریتی.
        /// </summary>
        internal static string ManagementLogs {
            get {
                return ResourceManager.GetString("ManagementLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدل رفتاری بازار.
        /// </summary>
        internal static string MarketBehaviorModeling {
            get {
                return ResourceManager.GetString("MarketBehaviorModeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت مدل ها.
        /// </summary>
        internal static string ModelManagement {
            get {
                return ResourceManager.GetString("ModelManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزش در خطر سهام.
        /// </summary>
        internal static string MR1 {
            get {
                return ResourceManager.GetString("MR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزش در خطر کل.
        /// </summary>
        internal static string MR2 {
            get {
                return ResourceManager.GetString("MR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توزیع سنجی.
        /// </summary>
        internal static string MR3 {
            get {
                return ResourceManager.GetString("MR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پورتفوی.
        /// </summary>
        internal static string MR4 {
            get {
                return ResourceManager.GetString("MR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد بهره خالص.
        /// </summary>
        internal static string NetInterestIncome {
            get {
                return ResourceManager.GetString("NetInterestIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احتمال نکول.
        /// </summary>
        internal static string PD {
            get {
                return ResourceManager.GetString("PD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش بازه سازی.
        /// </summary>
        internal static string RangeLoanReport {
            get {
                return ResourceManager.GetString("RangeLoanReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطبیق.
        /// </summary>
        internal static string Reconciliation {
            get {
                return ResourceManager.GetString("Reconciliation", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap S_ch_AggregatedValuesDown {
            get {
                object obj = ResourceManager.GetObject("S_ch_AggregatedValuesDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap S_ch_AggregatedValuesDown_Hover {
            get {
                object obj = ResourceManager.GetObject("S_ch_AggregatedValuesDown_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap S_ch_AggregatedValuesUp {
            get {
                object obj = ResourceManager.GetObject("S_ch_AggregatedValuesUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap S_ch_AggregatedValuesUp_Hover {
            get {
                object obj = ResourceManager.GetObject("S_ch_AggregatedValuesUp_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap S_ch_CurrentStDown {
            get {
                object obj = ResourceManager.GetObject("S_ch_CurrentStDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap S_ch_CurrentStDown_Hover {
            get {
                object obj = ResourceManager.GetObject("S_ch_CurrentStDown_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap S_ch_CurrentStUp {
            get {
                object obj = ResourceManager.GetObject("S_ch_CurrentStUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap S_ch_CurrentStUp_Hover {
            get {
                object obj = ResourceManager.GetObject("S_ch_CurrentStUp_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap S_ch_ForcastStDown {
            get {
                object obj = ResourceManager.GetObject("S_ch_ForcastStDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap S_ch_ForcastStDown_Hover {
            get {
                object obj = ResourceManager.GetObject("S_ch_ForcastStDown_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap S_ch_ForcastStUp {
            get {
                object obj = ResourceManager.GetObject("S_ch_ForcastStUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap S_ch_ForcastStUp_Hover {
            get {
                object obj = ResourceManager.GetObject("S_ch_ForcastStUp_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات نمایش گزارش.
        /// </summary>
        internal static string SettingShowTitleOfColumn {
            get {
                return ResourceManager.GetString("SettingShowTitleOfColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش ویژه تسهیلات.
        /// </summary>
        internal static string SpecialReportLoan {
            get {
                return ResourceManager.GetString("SpecialReportLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدل بسته زمانی.
        /// </summary>
        internal static string TimeBucket {
            get {
                return ResourceManager.GetString("TimeBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر فعلی سیستم : {0}.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه کاربر : {0}.
        /// </summary>
        internal static string UserGroup {
            get {
                return ResourceManager.GetString("UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کاربران.
        /// </summary>
        internal static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
    }
}
