//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AliasName.
        /// </summary>
        internal static string AliasNameColumnForReport {
            get {
                return ResourceManager.GetString("AliasNameColumnForReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TablixMember&gt;&lt;KeepWithGroup&gt;After&lt;/KeepWithGroup&gt;&lt;/TablixMember&gt;&lt;TablixMember&gt;&lt;Group Name=&quot;Details&quot; /&gt;&lt;/TablixMember&gt;.
        /// </summary>
        internal static string DEFAULT_TABLIX_ROW_HIERARCHY {
            get {
                return ResourceManager.GetString("DEFAULT_TABLIX_ROW_HIERARCHY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل اکسل.
        /// </summary>
        internal static string ExcelFile {
            get {
                return ResourceManager.GetString("ExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Files|*.xlsx.
        /// </summary>
        internal static string ExcelFilter {
            get {
                return ResourceManager.GetString("ExcelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        internal static string Key_And {
            get {
                return ResourceManager.GetString("Key_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterparty.
        /// </summary>
        internal static string Key_Counterparty {
            get {
                return ResourceManager.GetString("Key_Counterparty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEY_FINISH_INDEX.
        /// </summary>
        internal static string KEY_FINISH_INDEX {
            get {
                return ResourceManager.GetString("KEY_FINISH_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  = .
        /// </summary>
        internal static string Key_Mosavi {
            get {
                return ResourceManager.GetString("Key_Mosavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VDepositReport_Historic.
        /// </summary>
        internal static string KEY_NameOfDepositReport {
            get {
                return ResourceManager.GetString("KEY_NameOfDepositReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VGReport_Historic.
        /// </summary>
        internal static string KEY_NameOfGuaranteeReport {
            get {
                return ResourceManager.GetString("KEY_NameOfGuaranteeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCompareOverdueAndCollactTarhiniReport.
        /// </summary>
        internal static string KEY_NameOfLoanComOverdueAndCollactVLReport {
            get {
                return ResourceManager.GetString("KEY_NameOfLoanComOverdueAndCollactVLReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLReport_Historic.
        /// </summary>
        internal static string KEY_NameOfLoanReport {
            get {
                return ResourceManager.GetString("KEY_NameOfLoanReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLoanByCollactDetails.
        /// </summary>
        internal static string Key_NameOfVLoanByCollactDetailsReport {
            get {
                return ResourceManager.GetString("Key_NameOfVLoanByCollactDetailsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Key_OneNumber {
            get {
                return ResourceManager.GetString("Key_OneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  OR .
        /// </summary>
        internal static string Key_OR {
            get {
                return ResourceManager.GetString("Key_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string Key_Parantez_Baste {
            get {
                return ResourceManager.GetString("Key_Parantez_Baste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEY_SelectedColumn.
        /// </summary>
        internal static string KEY_SelectedColumn {
            get {
                return ResourceManager.GetString("KEY_SelectedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Key_SpaceString {
            get {
                return ResourceManager.GetString("Key_SpaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEY_START_INDEX.
        /// </summary>
        internal static string KEY_START_INDEX {
            get {
                return ResourceManager.GetString("KEY_START_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHERE_KEY.
        /// </summary>
        internal static string KEY_WHERE {
            get {
                return ResourceManager.GetString("KEY_WHERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100000.
        /// </summary>
        internal static string MaxSizeOfRowForReport {
            get {
                return ResourceManager.GetString("MaxSizeOfRowForReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameColumn.
        /// </summary>
        internal static string NameColumnForReport {
            get {
                return ResourceManager.GetString("NameColumnForReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string ParantezBaz {
            get {
                return ResourceManager.GetString("ParantezBaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string StartIndexForReportShow {
            get {
                return ResourceManager.GetString("StartIndexForReportShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Report xmlns:rd=&quot;http://schemas.microsoft.com/SQLServer/reporting/reportdesigner&quot; xmlns=&quot;http://schemas.microsoft.com/sqlserver/reporting/2008/01/reportdefinition&quot;&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;DataSource Name=&quot;Risk_Mng_MehrDataSet&quot;&gt;
        ///      &lt;ConnectionProperties&gt;
        ///        &lt;DataProvider&gt;System.Data.DataSet&lt;/DataProvider&gt;
        ///        &lt;ConnectString&gt;/* Local Connection */&lt;/ConnectString&gt;
        ///      &lt;/ConnectionProperties&gt;
        ///      &lt;rd:DataSourceID&gt;9bcb0ee7-1d04-4b57-8d26-818890c3e3a5&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strReportTemplate {
            get {
                return ResourceManager.GetString("strReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select KEY_SelectedColumn   from 
        ///
        ///(select 
        ///ROW_NUMBER() over(order by(SUM(Collateral.Collat_Value_Tarhini))) as Row_Id,
        /// SUM(Collateral.Collat_Value_Tarhini) as Collat_Value_Tarhini,sum(Loan_Contract.TotalOverdue)/COUNT(*) as TotalOverdue,
        ///sum(loan_contract.Approved_Amount)/COUNT(*) as Approved_Amount,
        ///Organization.Branch_Description,
        ///dbo.City.City_Name,
        ///STATe.State_Name,
        ///Collateral.Contract,
        ///Contract_Status.Status_Desc,
        ///Contract_Type.Contract_Type_Description,
        ///dbo.Economic_Sector.Economic_Sect [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructureQueryForReport_CompareOverdueAndCollateralTarhini {
            get {
                return ResourceManager.GetString("StructureQueryForReport_CompareOverdueAndCollateralTarhini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TablixCell&gt;&lt;CellContents&gt;&lt;Textbox Name=&quot;{0}&quot;&gt;&lt;CanGrow&gt;true&lt;/CanGrow&gt;&lt;KeepTogether&gt;true&lt;/KeepTogether&gt;&lt;Paragraphs&gt;&lt;Paragraph&gt;&lt;TextRuns&gt;&lt;TextRun&gt;&lt;Value&gt;=Fields!{1}.Value&lt;/Value&gt;&lt;Style&gt;&lt;FontFamily&gt;Tahoma&lt;/FontFamily&gt;&lt;Color&gt;#4d4d4d&lt;/Color&gt;&lt;/Style&gt;&lt;/TextRun&gt;&lt;/TextRuns&gt;&lt;Style /&gt;&lt;/Paragraph&gt;&lt;/Paragraphs&gt;&lt;rd:DefaultName&gt;{2}&lt;/rd:DefaultName&gt;&lt;Style&gt;&lt;Border&gt;&lt;Color&gt;#e5e5e5&lt;/Color&gt;&lt;Style&gt;Solid&lt;/Style&gt;&lt;/Border&gt;&lt;PaddingLeft&gt;2pt&lt;/PaddingLeft&gt;&lt;PaddingRight&gt;2pt&lt;/PaddingRight&gt;&lt;PaddingTop&gt;2pt&lt;/PaddingTop&gt;&lt;PaddingBottom&gt;2pt&lt;/P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TABLIX_CELL {
            get {
                return ResourceManager.GetString("TABLIX_CELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TablixCell&gt;&lt;CellContents&gt;&lt;Textbox Name=&quot;{0}&quot;&gt;&lt;CanGrow&gt;true&lt;/CanGrow&gt;&lt;KeepTogether&gt;true&lt;/KeepTogether&gt;&lt;Paragraphs&gt;&lt;Paragraph&gt;&lt;TextRuns&gt;&lt;TextRun&gt;&lt;Value&gt;{1}&lt;/Value&gt;&lt;Style&gt;&lt;FontFamily&gt;Tahoma&lt;/FontFamily&gt;&lt;FontSize&gt;11pt&lt;/FontSize&gt;&lt;FontWeight&gt;Bold&lt;/FontWeight&gt;&lt;Color&gt;White&lt;/Color&gt;&lt;/Style&gt;&lt;/TextRun&gt;&lt;/TextRuns&gt;&lt;Style /&gt;&lt;/Paragraph&gt;&lt;/Paragraphs&gt;&lt;rd:DefaultName&gt;{2}&lt;/rd:DefaultName&gt;&lt;Style&gt;&lt;Border&gt;&lt;Color&gt;#7292cc&lt;/Color&gt;&lt;Style&gt;Solid&lt;/Style&gt;&lt;/Border&gt;&lt;BackgroundColor&gt;#4c68a2&lt;/BackgroundColor&gt;&lt;PaddingLeft&gt;2pt&lt;/PaddingLeft&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TABLIX_CELL_LABEL {
            get {
                return ResourceManager.GetString("TABLIX_CELL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TablixMember /&gt;.
        /// </summary>
        internal static string TABLIX_MEMBER {
            get {
                return ResourceManager.GetString("TABLIX_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TablixMember&gt;&lt;KeepWithGroup&gt;After&lt;/KeepWithGroup&gt;&lt;/TablixMember&gt;.
        /// </summary>
        internal static string TABLIX_ROW_HIERARCHY_DEFAULT {
            get {
                return ResourceManager.GetString("TABLIX_ROW_HIERARCHY_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TablixMember&gt;&lt;Group Name=&quot;Details&quot; /&gt;&lt;/TablixMember&gt;.
        /// </summary>
        internal static string TABLIX_ROW_HIERARCHY_FILL_DEFAULT {
            get {
                return ResourceManager.GetString("TABLIX_ROW_HIERARCHY_FILL_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TablixColumn&gt;&lt;Width&gt;{0}in&lt;/Width&gt;&lt;/TablixColumn&gt;.
        /// </summary>
        internal static string TEMPLATE_COUNT_COLUMN {
            get {
                return ResourceManager.GetString("TEMPLATE_COUNT_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Name=&quot;{0}&quot;&gt;&lt;DataField&gt;{1}&lt;/DataField&gt;&lt;rd:TypeName&gt;{2}&lt;/rd:TypeName&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string TEMPLATE_FIELD {
            get {
                return ResourceManager.GetString("TEMPLATE_FIELD", resourceCulture);
            }
        }
    }
}
